version: "3.3"
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: "landing"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_ROOT_PASSWORD: "admin"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
  api:
    build:
      context: ./
      dockerfile: api.dockerfile
    env_file: .env
    command: sh -c "npm start"
    ports:
      - "7070:7070"
      # this port is for the node debugger
      - "9299:9299"
    expose:
      - "7070"
    working_dir: /api
    # this enables hot reloading by binding the source code directory to the working directory of the container
    volumes:
      - ./src:/src
    depends_on:
      - db
volumes:
  my-db:
